<?php
/**
 * Softnoesis
 * Copyright(C) 04/2023 Softnoesis <ideveloper1990@gmail.com>
 * @package Softnoesis_CancelOrder
 * @copyright Copyright(C) 2015 Softnoesis (ideveloper1990@gmail.com)
 * @author Softnoesis <ideveloper1990@gmail.com>
 */

?>
<?php $_orders = $block->getOrders(); ?>
<?= $block->getChildHtml('info') ?>
<?php if ($_orders && count($_orders)): ?>
    <div class="table-wrapper orders-history">
        <table class="data table table-order-items history" id="my-orders-table">
            <caption class="table-caption"><?= $block->escapeHtml(__('Orders')) ?></caption>
            <thead>
                <tr>
                    <th scope="col" class="col id"><?= $block->escapeHtml(__('Order #')) ?></th>
                    <th scope="col" class="col date"><?= $block->escapeHtml(__('Date')) ?></th>
                    <?= $block->getChildHtml('extra.column.header') ?>
                    <th scope="col" class="col shipping"><?= $block->escapeHtml(__('Ship To')) ?></th>
                    <th scope="col" class="col total"><?= $block->escapeHtml(__('Order Total')) ?></th>
                    <th scope="col" class="col status"><?= $block->escapeHtml(__('Status')) ?></th>
                    <th scope="col" class="col actions"><?= $block->escapeHtml(__('Action')) ?></th>
                </tr>
            </thead>
            <tbody>
                <?php foreach ($_orders as $_order): ?>
                    <tr>
                        <td data-th="<?= $block->escapeHtml(__('Order #')) ?>" class="col id"><?= $block->escapeHtml($_order->getRealOrderId()) ?></td>
                        <td data-th="<?= $block->escapeHtml(__('Date')) ?>" class="col date"><?= /* @noEscape */ $block->formatDate($_order->getCreatedAt()) ?></td>
                        <?php $extra = $block->getChildBlock('extra.container'); ?>
                        <?php if ($extra): ?>
                            <?php $extra->setOrder($_order); ?>
                            <?= $extra->getChildHtml() ?>
                        <?php endif; ?>
                        <td data-th="<?= $block->escapeHtml(__('Ship To')) ?>" class="col shipping"><?= $_order->getShippingAddress() ? $block->escapeHtml($_order->getShippingAddress()->getName()) : '&nbsp;' ?></td>
                        <td data-th="<?= $block->escapeHtml(__('Order Total')) ?>" class="col total"><?= /* @noEscape */ $_order->formatPrice($_order->getGrandTotal()) ?></td>
                        <td data-th="<?= $block->escapeHtml(__('Status')) ?>" class="col status"><?= $block->escapeHtml($_order->getStatusLabel()) ?></td>
                        <td data-th="<?= $block->escapeHtml(__('Actions')) ?>" class="col actions">
                            <a href="<?= $block->escapeUrl($block->getViewUrl($_order)) ?>" class="action view">
                                <span><?= $block->escapeHtml(__('View Order')) ?></span>
                            </a>
                            <?php if ($this->helper(\Magento\Sales\Helper\Reorder::class)->canReorder($_order->getEntityId())): ?>
                                <a href="#" data-post='<?= /* @noEscape */
                                $this->helper(\Magento\Framework\Data\Helper\PostHelper::class)
                                    ->getPostData($block->getReorderUrl($_order))
                                ?>' class="action order">
                                    <span><?= $block->escapeHtml(__('Reorder')) ?></span>
                                </a>
                            <?php endif ?>
                            <?php if ($_order->getStatusLabel() == 'Pending' && $this->helper(\Softnoesis\CancelOrder\Helper\Data::class)->getOrderRequest($_order->getEntityId()) == 'false'): ?>
                            <a  class="ks-cancel-order" href="#"  >
                              <span>
                                
                                <?php if ($this->helper(\Softnoesis\CancelOrder\Helper\Data::class)->getGeneralConfig('button_text')!= ''): ?>
                                    <?= $block->escapeHtml(__($this->helper(\Softnoesis\CancelOrder\Helper\Data::class)->getGeneralConfig('button_text'))) ?>
                                <?php else: ?>
                                    <?= $block->escapeHtml(__('Cancel Order')); ?>
                                <?php endif ; ?>
                                        
                              </span>
                            </a>
                            <div id="order-data" style="display:none;">
                                <input type="hidden" class="orderId" value="<?php echo $_order->getEntityId();?>"/>
                                <input type="hidden" class="orderstatus" value="<?php echo $_order->getStatusLabel();?>"/>
                                <input type="hidden" class="orderstate" value="<?php echo $_order->getState();?>"/>            
                            </div>
                            <?php elseif ($_order->getStatusLabel() == 'Pending' && $this->helper(\Softnoesis\CancelOrder\Helper\Data::class)->getOrderRequest($_order->getEntityId()) == 'true'): ?>
                                <span><?= $block->escapeHtml(__('Order Cancellation in progress...')); ?></span>
                            <?php endif ?>
                        </td>
                    </tr>
                <?php endforeach; ?>
                <div id="popup-modal-ordercancel" style="display:none;">
                    <p class="popup-lable"> Are you sure to cancel your order?</p> 
                    <form action="" method="post" id="cancel-request"  enctype="multipart/form-data" autocomplete="off" data-mage-init='{ "validation":{}}' >
                        <textarea id='comment' name = 'comment' maxlength="350" class='comment' placeholder='Please specify the reason for order cancelling.' ></textarea>
                        <div class="message-lable" id='message'><?= $block->escapeHtml(__($this->helper(\Softnoesis\CancelOrder\Helper\Data::class)->getGeneralConfig('popup_text'))) ?></div>
                    </form>
                </div>
            </tbody>
        </table>
    </div>
    <?php if ($block->getPagerHtml()): ?>
        <div class="order-products-toolbar toolbar bottom"><?= $block->getPagerHtml() ?></div>
    <?php endif ?>
<?php else: ?>
    <div class="message info empty"><span><?= $block->escapeHtml(__('You have placed no orders.')) ?></span></div>
<?php endif ?>

<script>

      require(
       [
           'jquery',
           'Magento_Ui/js/modal/modal'
       ],
       function (
           $,
           modal
       ) {
            $('.ks-cancel-order').on('click',function(e){
                var self = $(this);
                $("#comment").val('');

                var modaloption = {
                    type: 'popup',
                    modalClass: 'modal-popup-ordercancel',
                    responsive: true,
                    title: 'Order Cancellation Confirmation',
                    innerScroll: false,
                    clickableOverlay: true,
                    modalcloseBtn: true,
                    buttons: [{
                          text: $.mage.__('Cancel'),
                          class: '',
                          click: function () {
                              this.closeModal();
                          },
                          
                     },
                     {
                          text: $.mage.__('Submit Request'),
                          class: 'action-primary',
                          click: function () {
                              var form_data = $("#comment").val();
                              var orderId = self.closest('tr').find(".orderId").val();
                              var orderstatus = self.closest('tr').find(".orderstatus").val();
                              var orderstate = self.closest('tr').find(".orderstate").val();
                              console.log(form_data);
                              jQuery('#ajax_loader1').show();
                              $.ajax({
                                  url: "<?php  echo $block->getBaseUrl() . 'cancelorder/Index/Config';?>",
                                  type: 'POST',
                                  showLoader: true,
                                  data: { 'reason' : form_data, 'state' : orderstate, 'status' : orderstatus, 'entityId': orderId },
                                   complete: function(){
                                    window.location.reload();
                                   }
                              });
                              this.closeModal();
                          }
                    }]
               };
               var callforoption = modal(modaloption, $('#popup-modal-ordercancel'));
               $('#popup-modal-ordercancel').modal('openModal');

            });
       }
   );
</script>
    